### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-6#1]
za duzo console.log
- [x] w returnie zwracaj w funkcji tylko wynik samego dzialania
- [x] wtedy bedziesz mogla wyswietlac wynik dzialania funkcji, ktory masz juz w zmiennej w ten sposob: `console.log(triangle1Area);` - i tak dla wszystkich 3
- [x] w elsie nie potrzebujesz kolejnego ifa, ktory sprawdza to samo, tylko od drugiej strony

**Comment by JoannaKu** [comment]
nie wiem czy dobrze zrozumiałam o co chodziło Ci z tym ifem na końcu. wysłyłam tak jak zrobiłam :)

**Comment by michal-bootcamp** [comment]
- [ ] z returnem chodzilo mi o cos takiego: `return a*h/2` - console.log jest tam niepotrzebny
- [ ] dobrze, ze nadmiarowego ifa usunelas, przenies jeszcze else do linii wyzej, zeby sformatowane to bylo tak: `} else {`
- [ ] wyswietlasz na koncu tylko zawartosc `triangle1Area`, a masz jeszcze dwie zmienne, ktorym przypisujesz wynik dzialania funkcji getTriangleArea() z roznymi parametrami. Wyswietl je rowniez

**Comment by JoannaKu** [comment]
poprawione. o to chodziło z wyświetlaniem zmiennymi?

**Comment by michal-bootcamp** [comment]
z wyswietlaniem zmiennych nie, poniewaz ich nie wyswietlasz :) zmienna to jest to, co po var czyli np `triangle1Area` i ona przechowuje wynik dzialania funkcji.

Tutaj chodzi o to, zeby wyswietlic ta zmienna, tak jak mialas wczesniej, ale nie tylko `triangle1Area`, ale tez dwie pozostale zmienne

**Comment by JoannaKu** [comment]
dodałam trzy zmienne do wyświetlenia: triangle1Area, triangle2Area, triangle3Area. Powinnam jeszcze gdzieś dopisać a i h ?

**Comment by michal-bootcamp** [comment]
No i tak jest dobrze. Mozesz tez usunac `var a, h;` poniewaz te zmienne zupelnie nie maja zwiazku z parametrami, ktore definiujesz przy deklaracji w funkcji.

taki zapis:
`function getTriangleArea(a, h) { ... }`
mowi, ze definiujesz funkcje getTriangleArea, ktora przyjmuje dwa argumenty/parametry, ktore wewnatrz niej beda sie nazywaly a, h.

Czyli wywolujac funkcje w ten sposob:
`getTriangleArea(10, 6);` 
wewnatrz funkcji a=10, h=6.
jak wywolasz ja z innymi parametrami, to a i h beda inne.

To co zwraca funkcja przez return przypisujesz do zmiennej tutaj:
`var triangle1Area = getTriangleArea(10, 6);`
a potem tylko wyswietlasz zawartosc tej zmiennej:
`console.log(triangle1Area);`

Czyli prosze usun jeszcze tylko `var a, h;`

**Comment by JoannaKu** [comment]
ok, zrozumiałam. Teraz ma to sens :)
